---
- hosts: all
  become: yes
  tasks:
    - name: Install vsftpd
      yum:
        name: vsftpd
        state: installed
      tags: [never, alpha]
      
    - name: Install httpd
      yum:
        name: httpd
        state: installed
      tags: [never, beta]
...        
