---
- hosts: all
  become: yes
  tasks:
    - name: Install vsftpd
      yum:
        name: vsftpd
        state: present
      tags: [never, alpha]
    - name: Install apache
      yum:
        name: httpd
        state: present
      tags: [never, beta]  
...        
